name = "backend"
compatibility_date = "2024-08-11"

[vars]

DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNjJjZDQ0MWUtZmMzMC00Mjg2LWExNjctZjY1YjM4ZDIyMTI2IiwidGVuYW50X2lkIjoiZDA0MWJiODQwMDUyZjhiNTliMTc1NDIwNTMyYTQ4NTFmNjQzNThiOWNmYjEyMGFmOTU0N2FiMjUxNGIwOTRhZiIsImludGVybmFsX3NlY3JldCI6IjEyZTkyZTVlLTEyZGEtNGMyNi1hZGNiLWJiZWRmNjgxZmQzYiJ9.s_T7oeme7w7NoAd1lEaIZcPuzmQTY9ZlZqWq07WYzy4"
